name: another repository(check)
on: pull_request
jobs:
  check_secrets_head:
    if: "${{ github.event.pull_request.head.repo.full_name != github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
      - run: echo $var
        env:
          TOKEN: ${{secrets.TOKEN}}
          var: ${{vars.KEY}}
  check_secrets_base:
    if: "${{ github.event.pull_request.head.repo.full_name != github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.base_ref}}
      - run: echo $var
        env:
          TOKEN: ${{secrets.TOKEN}}
          var: ${{vars.KEY}}
